import * as E from "fp-ts/Either";
import * as RTE from "fp-ts/ReaderTaskEither";
import { pipe } from "fp-ts/function";

import * as Api from "./api";
import { Env } from "./types";

const schema = {
  schema: {
    properties: {
      firstName: {
        type: "string",
        label: "First Name",
      },
      lastName: {
        type: "string",
        label: "Last Name",
      },
      email: {
        type: "string",
        label: "Email Address",
        format: "email",
      },
      phone: {
        type: "string",
        label: "Phone Number",
        format: "phone",
      },
      date: {
        type: "string",
        label: "Date",
      },
      country: {
        type: "string",
        label: "Country",
      },
      postalCode: {
        type: "string",
        label: "Postal Code",
      },
      optIn: {
        type: "boolean",
        label: "Opt In",
      },
      dealStatus: {
        type: "string",
        label: "Deal Status",
        enumLabel: [
          "Prospecting",
          "Discovery",
          "Proposal",
          "Negotiation",
          "Closed Won",
          "Closed Lost",
        ],
        enum: ["Prospecting", "Discovery", "Proposal", "Negotiation", "Closed Won", "Closed Lost"],
      },
    },
    type: "object",
    required: ["lastName"],
    unique: ["email"],
  },
};

const main = async () => {
  try {
    const env: Env = {
      accessKeyId: process.env.FLATFILE_ACCESS_KEY_ID || "",
      apiHost: process.env.FLATFILE_API_HOST || "",
      secretAccessKey: process.env.FLATFILE_SECRET_ACCESS_KEY || "",
      accessToken: "",
    };

    if (env.accessKeyId === "" || env.secretAccessKey === "") {
      throw "Ensure both FLATFILE_ACCESS_KEY_ID and FLATFILE_SECRET_ACCESS_KEY env vars are set";
    }

    const tokenPromise = Api.createToken()(env);
    const token = await tokenPromise();

    pipe(
      token,
      E.match(
        () => {
          throw "Failed to create token";
        },
        async (accessToken) => {
          const pipelinePromise = Api.createTemplate(
            "34661",
            "AutoGenerated5",
            schema,
          )({ ...env, accessToken });

          const template = await pipelinePromise();
          console.log(template);
        },
      ),
    );
  } catch (err) {
    console.error(`Error: ${err}!`);
  }
};

main();
